# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import monitors.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Select a label for your collection of tweets.', max_length=100)),
                ('type', models.CharField(choices=[('Search', 'Search'), ('Stream', 'Stream')], max_length=20)),
                ('follow', models.TextField(blank=True, help_text='A comma separated list of user IDs, indicating the users to return statuses for in the stream. More information at https://dev.twitter.com/docs/streaming-apis/parameters#follow', null=True, validators=[monitors.models.list_of_ids], verbose_name='List of User IDs to follow (separated with commas)')),
                ('track', models.TextField(blank=True, help_text='A comma separated list of keywords or phrases to track. Phrases of keywords are specified by a comma-separated list. More information at https://dev.twitter.com/docs/streaming-apis/parameters#track', null=True, verbose_name='List of keywords to track (separated with commas)')),
                ('locations', models.TextField(blank=True, help_text='A comma-separated list of longitude,latitude pairs specifying a set of bounding boxes to filter Tweets by. On geolocated Tweets falling within the requested bounding boxes will be included\u2014unlike the Search API, the user\'s location field is not used to filter tweets. Each bounding box should be specified as a pair of longitude and latitude pairs, with the southwest corner of the bounding box coming first. For example: "-122.75,36.8,-121.75,37.8" will track all tweets from San Francisco. NOTE: Bounding boxes do not act as filters for other filter parameters. More information at https://dev.twitter.com/docs/streaming-apis/parameters#locations', null=True, verbose_name='List of coordinates')),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
