# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='type',
            field=models.CharField(choices=[('search', 'search'), ('stream', 'stream')], max_length=20),
        ),
    ]
