# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import monitors.models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0002_auto_20160830_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='language',
            field=models.CharField(blank=True, help_text='Select a language find codes at http://www.andiamo.co.uk/resources/iso-language-codes ', max_length=100),
        ),
        migrations.AddField(
            model_name='monitor',
            name='result_type',
            field=models.CharField(blank=True, choices=[('popular', 'popular'), ('recent', 'recent'), ('mix', 'mix')], help_text='You cna chose a specific type of result generated by twitter', max_length=20),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='follow',
            field=models.TextField(blank=True, help_text='Works only for Stream API ... A comma separated list of user IDs, indicating the users to return statuses for in the stream. More information at https://dev.twitter.com/docs/streaming-apis/parameters#follow', null=True, validators=[monitors.models.list_of_ids], verbose_name='List of User IDs to follow (separated with commas)'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='track',
            field=models.TextField(blank=True, help_text='A comma separated list of keywords or phrases to track. Phrases of keywords are specified by a comma-separated list. More information at https://dev.twitter.com/docs/streaming-apis/parameters#track and https://dev.twitter.com/rest/public/search', null=True, verbose_name='List of keywords to track (separated with commas)'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='type',
            field=models.CharField(choices=[('search', 'search'), ('stream', 'stream')], help_text='Chose between search or stream API', max_length=20),
        ),
    ]
