# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0005_auto_20160915_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='language',
            field=models.CharField(blank=True, default=None, help_text='Select a language find codes at http://www.andiamo.co.uk/resources/iso-language-codes ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='result_type',
            field=models.CharField(blank=True, choices=[('popular', 'popular'), ('recent', 'recent'), ('mix', 'mix')], default=None, help_text='You cna chose a specific type of result generated by twitter', max_length=20, null=True),
        ),
    ]
