# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0010_auto_20160915_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='result_type',
            field=models.CharField(blank=True, choices=[('popular', 'popular'), ('recent', 'recent'), ('mixed', 'mixed')], default='mixed', help_text='You cna chose a specific type of result generated by twitter', max_length=20),
        ),
    ]
