# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0012_auto_20160916_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='follow',
            field=models.TextField(blank=True, help_text='Works only for Stream API ... A comma separated list of user IDs,\n indicating the users to return statuses for in the stream. More information at https://dev.twitter.com/docs/streaming-apis/parameters#follow', null=True, verbose_name='List of User IDs to follow (separated with commas)'),
        ),
    ]
